Main page added
n-gurkov/my-favorite-movies-frontend pull request #3
Opened 2023-03-27 14:56 UTC by n-gurkov

- Main page added
- Block-view added

2023-03-28 12:15 UTC, Isidora25 requested changes

2023-03-28 12:15 UTC, Isidora25 commented on src/App.tsx
> +        <Route path='/AddMoviePage' />
url обычно пишутся в kebab-case

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/Header/Header.tsx
> +      <p onClick={() => navigate("/main-page")}>My favorite movies</p>
если есть i18n все отображаемые тексты должны быть в локалях

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/Header/Header.tsx
> +      <p onClick={() => navigate("/main-page")}>My favorite movies</p>
если элемент кликабельный и редиректит куда-то  - это ссылка

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/Header/assets/styles.ts
> +    margin-bottom: 1rem;
удобно заменить сокращением` margin: 1rem 0;`

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/Header/assets/styles.ts
> +export const CaptionWrapper = styled(HeaderWrapper)`
отделяй пробелами константы со стилями, так удобнее читать

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/Header/assets/styles.ts
> +    margin-right: 20rem;
то же самое, используй сокращение margin: 0 20rem;

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/MainPage.tsx
> +        <button onClick={LogOut}>{t('mainPage.logout')}</button>
то что кликается и редиректит - ссылка, не редиректит - кнопка

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +  margin-right: 1rem;
сокращения

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +  right: 0;
зачем [a](position: absolute;)? по виду элемент и находится в нормально потоке
еслли нужно прикрепить к правой стороне - используй стандартное позиционирование - флекс, грид, автоматический margin

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +  box-shadow: ${(props) => (props.isChecked ? '0px 0px 10px gray' : '0px')};
скрыть box-shadow => box-shadow: none

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/MainPage.tsx
> +import plus from 'src/Components/MainPage/assets/plus.svg';
почему по по полному урлу импортируешь? гораздо короче делать это ./assets/icon.svg
Components - папки не реакт компонентов с маленькой буквы именуются

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/MainPage.tsx
> +import { CaptionWrapper } from '../Header/assets/styles';
если какие-то стили используются в нескольких местах, то их нужно выносить на глобальный уровень
представь, что ты удалишь компонент header за ненадобностью, тогда сломаются все компоненты, которые использовали его стили

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/MainPage.tsx
> +import { CaptionWrapper } from '../Header/assets/styles';
кстати styles обычно хранят там же, где сам компонент

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/MainPage.tsx
> +          <img src={plus} />
img положено задавать аттрибут alt

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +import styled from 'styled-components';
переименуй этот файл просто в styles

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +export const GenreCard = styled.div<{ isChecked?: boolean }>`
GenreCard не используется в MainPage, ему здесь не место 
перенеси туда, где он используется

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/MainPage.tsx
> +      <div>
старайся избегать таких пустых оберток, скорее всего можно обойтись и без нее

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +export const GenresWrapper = styled.div`
этому тоже здесь не место

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +export const MovieWrapperBlock = styled.div`
а это вообще не используется, все что не используется, должно быть удалено

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +`;
тоже убирай отсюда

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +    props.isBlockView ? 'flex-direction: row' : 'flex-direction: column'};
```suggestion
  flex-direction: ${(props) =>
    props.isBlockView ? 'row' : 'column'};
```

так короче и нет дуюлирующихся слов

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +
лишних пробелов тоже не должно быть

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +  ${(props) => (props.isBlockView ? 'width: 30%;' : 'width: 98%;')};
тут тоже переделай как в примере выше для flex-direction

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +export const ButtonsWrapper = styled(LogoutForm)`
для чего ты постоянно перестиливаешь уже созданные компоненты? 
если придется поменять LogoutForm, то ButtonsWrapper тоже поменяется
будет очень грустно 
просто стиль обычные теги

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +  height: 30px;
Button - это обстилинная Card?
котопес какой-то 
во-первых, Button должен быть button 
а во-вторых, пусть он будет самостоятельный

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/assets/MainPageStyledComponents.ts
> +  height: auto;
почему не img?

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/components/GenresSelector/GenresSelector.tsx
> +      let genreId = genresId.indexOf(id);
если genreId не меняется, то это const

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/components/GenresSelector/components/GenresList.tsx
> +      {genres.map((genre: any) => {
ты наверняка знаешь, какая структура у genre - используй этот тип здесь

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/components/GenresSelector/components/GenresList.tsx
> +}
удобнее хранить описания типов в отдельных файлах types.ts - тогда тело компонента не разрастается

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/components/GenresSelector/components/GenresList.tsx
> +  genresId: IGenre[];
почему genresId хранит то же самое, что и genres
логично было бы genresId иметь как массив, в котором только id

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/components/GenresSelector/components/GenresList.tsx
> +            isChecked={genresId.includes(genre.id) ? true : false}
includes(genre.id) уже возвращает true или false

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/components/MyMovies/MyMovies.tsx
> +    const watched: number[] = getLocalData('userMoviesIDs');
watched что? 
watchedMovies или watchedGenres 
назови подробнее

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/components/MyMovies/MyMovies.tsx
> +    <div>
тут точно div нужен?

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/components/MyMovies/components/MyMoviesList.tsx
> +            isWatched={movie.isWatched ? true : false}
isWatched уже true или false

2023-03-28 12:15 UTC, Isidora25 commented on src/Components/MainPage/components/MyMovies/components/MyMoviesList.tsx
> +            </div>
стили покинули чат, давай уж и тут красиво пусть будет

2023-03-28 12:15 UTC, Isidora25 commented on src/utils.tsx
> +}
вынеси в отдельный файл

2023-03-28 12:15 UTC, Isidora25 commented on src/utils.tsx
> +    watched = watched.filter((item) => item !== id);
зачем ты мутируешь входящий параметр, делай сразу return

2023-03-28 12:15 UTC, Isidora25 commented on src/utils.tsx
> +export const addWatched = (id: number) => {
отбивай пробелами

2023-03-28 12:15 UTC, Isidora25 commented on src/utils.tsx
> +    let watched: number[] = JSON.parse(
ты не меняешь watched, используй const

2023-03-28 12:15 UTC, Isidora25 commented on src/utils.tsx
> +  localStorage.setItem('userMoviesIDs', JSON.stringify(remove));
ты стреляешь себе в ногу 
заведи еще одну переменную, если нужно 
невозможно понять, что тут происходит

2023-03-28 12:15 UTC, Isidora25 commented on src/utils.tsx
> +  isWatched?: boolean;
в js принято использовать camelCase, poster_path нужно исправить

2023-04-24 06:22 UTC, Isidora25 requested changes

2023-04-24 06:22 UTC, Isidora25 commented on src/Components/Header/assets/styles.ts
> +  padding: 1rem 1rem;
```suggestion
  padding: 1rem;
```

2023-04-24 06:22 UTC, Isidora25 commented on src/Components/MainPage/components/MyMovies/MyMovies.tsx
> +localStorage.setItem('userMoviesIDs', JSON.stringify([103, 15, 234]));
[magic numbers](https://jeffreyeverhart.com/2020/09/28/javascript-tips-using-named-constants-for-magic-numbers/)
вынеси в константу

2023-04-24 06:22 UTC, Isidora25 commented on src/utils.tsx
> +  console.log(item);
не стоит оставлять в коде логи

2023-04-24 06:22 UTC, Isidora25 commented on src/utils.tsx
> +  let remove = getLocalData('userMoviesIDs').filter(
если ты не меняешь переменную, то она должна быть объявлена с помощью const

2023-04-25 06:50 UTC, Isidora25 requested changes

2023-04-25 06:50 UTC, Isidora25 commented on src/utils.tsx
> +  return data != null ? JSON.parse(data) : [];
используй !== -оно безопаснее, потому что не делает автоматического приведения типов и не сможет скастить 
false и 0, например

2023-04-25 07:50 UTC, Isidora25 approved these changes

2023-04-25 08:35 UTC, reshetov requested changes

2023-04-25 08:35 UTC, reshetov commented on src/Components/MainPage/MainPage.tsx
> +  const LogOut = () => {
Тут у тебя нарушение SRP. Не нужно компоненту знать логику логина/логаута.
Вытащи это в отдельный сервис, а тут просто используй

2023-04-25 08:35 UTC, reshetov commented on src/Components/MainPage/MainPage.tsx
> +        <MainPageButton onClick={() => setView(true)} isChecked={isBlockView}>
`<MainPageButton onClick={() => setView(isBlockView)} isChecked={isBlockView}>` а так не прокатит? и ниже тоже самое

2023-04-25 08:35 UTC, reshetov commented on src/Components/MainPage/components/GenresSelector/GenresSelector.tsx
> +  useEffect(() => {
Отделяй константы и методы/хуки пустой строкой

2023-04-25 08:35 UTC, reshetov commented on src/Components/MainPage/components/GenresSelector/GenresSelector.tsx
> +    localStorage.setItem('userGenres', JSON.stringify(genres));
Я вижу что ты сохраняешь жанры в store но не вижу как они загружаются. Получается они вообще не используются.
Вытащи это лучше в отдельный сервис для работы с беком, который сейчас при обращении (загрузке приложения) будет отдавать данные из LS, а потом делать запрос на бек за ними. 
И для записи тоже нужен будет отдельный метод

2023-04-25 08:35 UTC, reshetov commented on src/Components/MainPage/components/MyMovies/MyMovies.tsx
> +const USER_MOVIES_IDS = [103, 15, 234, 24, 255, 77, 78, 28, 11];
Какие-то магические числа. Тоже самое - вынеси в сервис по работе с API который отдает пока их, а потом будет отдавать данные с бека

2023-04-25 08:35 UTC, reshetov commented on src/Components/MainPage/components/MyMovies/MyMovies.tsx
> +    const userMoviesIDs = getLocalData('userMoviesIDs');
Все это в сервис

2023-04-25 08:35 UTC, reshetov commented on src/Components/MainPage/components/MyMovies/MyMovies.tsx
> +    deleteFavorite(id);
Это все по идее тоже туда

2023-04-25 08:35 UTC, reshetov commented on src/Components/MainPage/components/MyMovies/MyMovies.tsx
> +    toggleWatched(id);
И это

2023-04-25 08:35 UTC, reshetov commented on src/utils.tsx
> +export interface IMovieResponse {
Вытащи интерфейсы в отдельный каталог types

2023-11-28 12:44 UTC, reshetov requested changes

2023-11-28 12:44 UTC, reshetov commented on src/utils.tsx
> +  localStorage.setItem('users', JSON.stringify(users))
Тут проверку бы добавить, сейчас каждый раз заново загружает пользователей

2023-11-28 12:44 UTC, reshetov commented on src/Hooks/useFavoriteMovies.tsx
> +    const index = watchedIds.findIndex((item) => item === id)
Чет ты перемудрил тут сильно nextWatchedIds вообще не нужно, ну или в константу ее поставь и через тернарник заполняй `const newWatchedIds = index > 0 ? .slice : .push`

2023-11-28 12:44 UTC, reshetov commented on src/Hooks/useGenres.tsx
> +  const [genresId, setGenresId] = useState<number[]>(userGenresIds)
Ids уж тогда

2023-11-28 12:44 UTC, reshetov commented on src/Hooks/useGenres.tsx
> +      const genreId = genresId.indexOf(id)
Тут лишние телодвижения. Сначала ты ищешь есть ли вообще id в массиве, потом ищешь его index. Почему сразу не проверить если index > 0 то удаляем, нет - добавляем

2023-11-28 12:44 UTC, reshetov commented on src/utils.tsx
> +  const users = getLocalData('users') || []
userPassword = (getLocalData('users') || [])[login]
return userPassword && userPassword != password

а все телодвижения ниже с localStorage нужно в отдельную функцию выносить (вроде loginUser) и вызывать как checkPassword(...) && loginUser() Либо тут функцию переименовывать. А то сейчас у тебя sideEffect прикольный, я пытаюсь проверить пароль - вжух и я уже залогиген почему-то

2023-11-29 06:11 UTC, reshetov requested changes

2023-11-29 06:11 UTC, reshetov commented on src/utils.tsx
> +  if (!checkPassword(login, password)) {
И зачем так сложно то у тебя checkPassword(login, password) и так выдает false если не прокатывает.
Плюс ты создаешь одну супер функцию, это прямое нарушение SRP, я же выше писал что можно разнести на 
`loginUser(...) => { checkPassword(...) && fillCurrentUser(...)}`
Так у тебя функция просто вызывает необходимые действия без вникания в их реализацию, при этом если пароль неправильный - вторая функция вызвана не будет

2023-11-30 06:30 UTC, reshetov approved these changes

2023-12-01 06:46 UTC, Isidora25 requested changes

2023-12-01 06:46 UTC, Isidora25 commented on src/Components/Header/Header.tsx
> +      <a onClick={() => navigate('/main-page')}>{t('header.title')}</a>
ну это какое-то извращение) 
если это ссылка, то у нее есть аттрибут href, onClick тут лишний

2023-12-01 06:46 UTC, Isidora25 commented on src/Components/LoginPage/components/LoginField.tsx
> +  isPassword?: boolean
функциональнее сделать текстовый проп type?: 'password' : 'text' и по умолчанию задать ему значение 'text'
это сделает компонент масштабируемым

2023-12-01 06:46 UTC, Isidora25 commented on src/Components/MainPage/MainPage.tsx
> +  const AddMovie = () => {
переменные в js именуются в camelCase 
PascalCase используется для классов

2023-12-01 06:46 UTC, Isidora25 commented on src/Components/MainPage/MainPage.tsx
> +        </MainPageButton>
если элемент куда-то перенаправляет юзера - это ссылка, а не кнопка

2023-12-01 06:46 UTC, Isidora25 commented on src/Components/MainPage/MainPage.tsx
> +        <LogoutLink onClick={logOut}>{t('mainPage.logout')}</LogoutLink>
зачем делать это линкой, если ты не используешь ее киллер-фичу атрибут href?

2023-12-01 08:29 UTC, Isidora25 approved these changes

2023-12-01 10:17 UTC, merged